### PR TITLE
Soheab patch 1

### PR DESCRIPTION
**Pull request by Soheab**
xD why not I got some people ask for it it’s stupid but 🤷‍♂️

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
So many commits, yet it was closed, lol

**Comment by Soheab** [comment]
> So many commits, yet it was closed, lol

You like them? 👀

**Comment by AlexFlipnote** [comment]
Kinda, but I won't really add such for this README right now.
Thanks for the suggestion otherwise.

**Comment by Soheab** [comment]
Ah well np :D

**Pull request closed without merging**
