### PR TITLE
[enhancement] Better prefixes

### PR DESCRIPTION
**Pull request by Nirlep5252**
Made it so that users can use the bot mention as a prefix like "@bot help" or leave spaces after the current prefix like "! help" to invoke a command.

### CODE REVIEW

**Comment by MrPotato374** [comment]
👀

**Comment by Nirlep5252** [comment]
👀

**Comment by Soheab** [comment]
👀

**Comment by AlexFlipnote** [comment]
This won't be added, to make this package as simple as possible, you control all prefix from the config.json file.

**Pull request closed without merging**
