### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by pieromqwerty**
This pull request configures this repository to be run on Repl.it.      It adds a `.replit` configuration file and a Repl.it badge to the `README`.
     You can read more about running repos on Repl.it [here](https://docs.repl.it/repls/dot-replit), or view the Repl [here](https://repl.it/@pieromqwerty/discordbotpy).

### CODE REVIEW

**Comment by Soheab** [comment]
Oh no, rep.it bad. If this gets approved i will add heroku shit

**Comment by Saederup92** [comment]
Hmm. Exactly how would that be benefitial?

**Comment by pieromqwerty** [comment]
@Soheab >:( fight me homie. Repl.it is actually fairly good. I don't see how you dislike it.
@Saederup92 This would make it easier for people to run the bot without any setup, asides from getting the actual discord api keys.

**Comment by Soheab** [comment]
Nah repl.it is bad and no one should recommend anyone to host a bot for free/on repl.it or heroku.

**Comment by AlexFlipnote** [comment]
Fellas, please don't fight over a PR.. 😦

While having a file for **repl.it** would be a nice touch to the repository, it would additionally create a butterfly effect where more services would be requested to the source too. I would suggest removing the dedicated file for it but rather keep the comment on README.md that there is an option to host it there otherwise.

Hope you understand my point of view.

**Comment by lorenzzzz** [comment]
i dont know what it is but yeah add it dunno do iT!

**Comment by pieromqwerty** [comment]
@AlexFlipnote the .replit file is what repl.it uses to know what language to use, and what to feed to the shell to have it run. This would allow for people to test out the bot quickly to see if it fits their needs, and they can quickly make any changes they like. If you don't want the file in your repo, I would be happy to fork this repo, and keep it updated in an operational form for repl.it, and you could just have a link to that. Would that be better for you?

**Comment by AlexFlipnote** [comment]
I noticed while trying out **repl.it** that you have the ability to choose Python as the source of your code and can afterwords create their own starter file to do the same task.
Image
Image2

That's why I said that mentioning it simply in README would be the easiest, as creating the new file and copy-pasting from README would be easier than adding more and more files to the repo to a point where it would have too many files for different services.

**Comment by pieromqwerty** [comment]
That is true, so just a simple note in the README should be fine, along with the button.

**Comment by AlexFlipnote** [comment]
That's all fine, just update your fork and I'll check your PR whenever that commit is done 🙂

**Comment by pieromqwerty** [comment]
@AlexFlipnote done!

**Pull request merged**
