### PR TITLE
added music cog

### PR DESCRIPTION
**Pull request by CS-ION**
Hello there, I have added music cog for your bot. The cog contains simple music commands for the bot to stream music in a discord voice channel. Do visit my repository to know more advanced stuff about the music commands. Cheers.

### CODE REVIEW

**Comment by Marck** [comment]
You forgot the following in the requirements.txt:
`youtube_dl
youtube-search-python`

**Comment by Marck** [comment]
Also running the join command when the bot is already in a channel gives an error. A check if the bot is already in a channel is better idea

**Comment by CS-ION** [comment]
Hello there. I am so sorry for my mistakes. I have updated the requirements.txt and also placed the check in join command as you said. Cheers

**Comment by AlexFlipnote** [comment]
Sadly I will decline this PR, due to the fact that this repository is meant to be easy to use, without needing to dive in to complication of streaming music right away, and rather have simple commands. Great concept, just not the right spot.

**Comment by CS-ION** [comment]
Oh okay. Thankyou. Cheers

**Pull request closed without merging**
